ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = 0.0.0.0
    }
    application {
        modules = [ com.absaide.server.ApplicationKt.module ]
    }
}

jwt {
    secret   = ${?JWT_SECRET}
    issuer   = ${?JWT_ISSUER}
    audience = ${?JWT_AUDIENCE}
    realm    = ${?JWT_REALM}
}

database {
    driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL         = ${?DATABASE_URL}
    username        = ${?DATABASE_USER}
    password        = ${?DATABASE_PASSWORD}
    maximumPoolSize = 10
}