ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = 0.0.0.0
    }
    application {
        modules = [ com.absaide.server.ApplicationKt.module ]
    }
}

jwt {
    secret   = "galery-absaide-secret-key-2024"
    issuer   = "galery-absaide"
    audience = "galery-absaide-users"
    realm    = "Galery Absaide"
}

database {
    driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL         = ${DATABASE_URL}
    username        = ${DATABASE_USER}
    password        = ${DATABASE_PASSWORD}
    maximumPoolSize = 10
}