ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.absaide.server.ApplicationKt.module ]
    }
}

jwt {
    secret   = "galery-absaide-secret-key-2024"
    issuer   = "galery-absaide"
    audience = "galery-absaide-users"
    realm    = "Galery Absaide"
}

database {
    driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL         = "jdbc:mysql://localhost:3306/galery_absaide?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    username        = "root"
    password        = ""
    maximumPoolSize = 10
}
